name: Daily Flat Scraper at 9 AM

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install beautifulsoup4
          pip install requests
          pip install pandas
          pip install numpy
          pip install psycopg2-binary 
          pip install supabase
          # smtplib is part of Python's standard library and doesn't need installation

      - name: Run Python script
        run: python flat_scraper.py
